AWS_ACCESS_KEY_ID = 'AKIAZQBHRBP3TDZOFSQ6'
AWS_SECRET_ACCESS_KEY = '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'
AWS_REGION = 'ap-northeast-2'
AWS_S3_BUCKET = 'ssafy-mmc'
AWS_S3_BUCKET_URL = 'https://s3.ap-northeast-2.amazonaws.com/ssafy-mmc'